---
title: "Dashboard of packages on CRAN"
output: github_document
format: gfm
default-image-extension: ""
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


get_badges <- function(pkg, repo = "andrie") {
  blob <- glue::glue("https://raw.githubusercontent.com/{repo}/{pkg}/main/README.Rmd")
  rmd <- readr::read_lines(blob)
  start <- grep("<!-- badges: start -->", rmd)
  end   <- grep("<!-- badges: end -->"  , rmd)
  badges <- rmd[(start + 1) : (end - 1)] 
  
  desc <- glue::glue("https://raw.githubusercontent.com/{repo}/{pkg}/main/DESCRIPTION")
  dcf <- readr::read_lines(desc)
  line <- grep("^Title", dcf)
  title <- dcf[line]
  
  cat(title)
  cat("\n\n")
  cat(badges)
  cat("\n\n")
  invisible(list(title, badges))
}


```

Andrie's dashboard with status of R packages on CRAN

## miniCRAN

<https://github.com/andrie/miniCRAN>

```{r}
#| echo: FALSE
#| output: asis
get_badges("miniCRAN")
```


## sss

<https://github.com/andrie/sss>

```{r}
#| echo: FALSE
#| output: asis
get_badges("sss")
```

## ggdendro


<https://github.com/andrie/ggdendro>

```{r}
#| echo: FALSE
#| output: asis
get_badges("ggdendro")
```

## surveydata


<https://github.com/andrie/surveydata>

```{r}
#| echo: FALSE
#| output: asis
get_badges("surveydata")
```

## rrd


<https://github.com/andrie/rrd>

```{r}
#| echo: FALSE
#| output: asis
get_badges("rrd")
```


## rfordummies


<https://github.com/andrie/rfordummies>

```{r}
#| echo: FALSE
#| output: asis
get_badges("rfordummies", "rfordummies")
```

# Posit

## config


<https://github.com/rstudio/config>

```{r}
#| echo: FALSE
#| output: asis
get_badges("config", "rstudio")
```
```


## sortable

<https://github.com/rstudio/sortable>

```{r}
#| echo: FALSE
#| output: asis
get_badges("sortable", "rstudio")
```




## nomnoml

<https://github.com/rstudio/nomnoml>

```{r}
#| echo: FALSE
#| output: asis
get_badges("nomnoml", "rstudio")
```



